spring.datasource.url=jdbc:postgresql://localhost:5432/booking_db
spring.datasource.username=booking_user
spring.datasource.password=booking_pass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true